version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ${APP_NAME}-php
        image: ${APP_NAME}-php
        volumes:
            -   .:/var/www
        networks:
            - to-backend-hismith

    nginx:
        image: nginx:alpine
        container_name: ${APP_NAME}-nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - to-backend-hismith

    postgres:
        image: postgres:12.4
        container_name: ${APP_NAME}-pgsql
        volumes:
            - pgsql-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: hismith
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        ports:
            - "5432:5432"
        networks:
            - to-backend-hismith

    redis:
        container_name: ${APP_NAME}-redis
        image: redis:alpine
        restart: unless-stopped
        networks:
            - to-backend-hismith

    php-queue:
        image: ${APP_NAME}-php
        container_name: ${APP_NAME}-queue
        entrypoint: /entrypoint-horizon
        restart: always
        command: php -dmemory_limit=512M artisan horizon
        working_dir: /var/www
        environment:
            - DB_HOST=postgres
        volumes:
            - ./:/var/www
        depends_on:
            - php
        networks:
            - to-backend-hismith

volumes:
    pgsql-data:
        driver: local

networks:
    to-backend-hismith:
        driver: bridge
